### ISSUE TITLE
Application 'angular' died in status LOADING_SOURCE_CODE: Cannot read property 'bootstrap' of undefined

### ISSUE THREAD

**Issue by prasekhar** [CanopyTax/single-spa-angular#123] opened 2019-12-26 01:45 UTC
I am getting LOADING_SOURCE_CODE error. I tried many times with different apps. still had the same issue.

import singleSpaAngular from 'single-spa-angular';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { NgZone } from '@angular/core';
import { Router } from '@angular/router';
import mainModule from './main-module.ts';
const lifecycles = singleSpaAngular({
  bootstrapFunction: singleSpaProps => {
    return platformBrowserDynamic().bootstrapModule(mainModule);
  },
  template: `<ang-app />`,
  Router,
  NgZone: NgZone,
});
export const bootstrap = lifecycles.bootstrap;
export const mount = lifecycles.mount;
export const unmount = lifecycles.unmount;

import {NgModule} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';
import {ExampleNg2App} from './example-ng2-app.component';
import {enableProdMode} from '@angular/core';

try {
    enableProdMode();
} catch (err) {
    console.info('EnableProdMode already set')
}

@NgModule({
    imports: [BrowserModule],
    declarations: [ExampleNg2App],
    bootstrap: [ExampleNg2App]
})
export default class MainModule {
}

registerApplication(
  'angular',
  ()=> import ('./src/angular/angular.app.js').then(module => {}),
  pathPrefix('/angularTs')
);

**Comment by joeldenning** [comment] 2019-12-30 17:46
I'd need more information to diagnose this. The full stacktrace from the browser would be the most useful to start. Also, a github repo that demonstrates the problem would be helpful.

**Comment by prasekhar** [comment] 2019-12-31 02:24
i have provided in the title. here is the github repo.

(https://github.com/prasekhar/micro-front-end/tree/develop)

**Comment by joeldenning** [comment] 2020-01-06 23:31
You did not provide a stacktrace.` Application 'angular' died in status LOADING_SOURCE_CODE: Cannot read property 'bootstrap' of undefined` is not a stacktrace. It is an error message. A stacktrace includes the call stack. Additionally in this case, there are two relevant stack traces and you have provided neither of them.

The `Cannot read property 'bootstrap' of undefined` error is a side effect of a different error. You should fix the other error and then that error will go away. When applications fail to mount, single-spa attempts to unmount them. Sometimes the unmounting fails directly because the mounting failed to work, and you get the `Cannot read property 'bootstrap' of undefined` error. However the root cause is actually that the mounting is happening in 

Your demo repo provides no instructions about how to reproduce the problem, which is a challenge. My guess is that you have failed to load ZoneJS into your html file (as [described here](https://single-spa.js.org/docs/ecosystem-angular#zonejs)) or you have failed to set the angular base href (as [described here](https://single-spa.js.org/docs/ecosystem-angular#configure-routes)). However, I cannot be certain since you've provided no context whatsoever on how to reproduce the error.

I'm closing this because I wasted time trying to figure it out when you didn't provide the relevant information for me to diagnose it. Feel free to reopen when you provide the stacktrace and instructions on how to reproduce the problem with your demo repo.

**Closed by joeldenning** 2020-01-06 23:31 UTC
