### ISSUE TITLE
FormGroup submit event refresh the page (navigate within app)

### ISSUE THREAD

**Issue by HemendPatel63** [CanopyTax/single-spa-angular#71] opened 2019-05-09 17:26 UTC
I have implemented the lazy loading with latest version( v3.0.0-beta.20) and after that FormGroup submit event refresh the page if you navigate within the app.

i.e formgroup is use on homecomponent in APP1
Then-
routes
1 Home to Dashboard
2 Dashboard to Home  
3. Now submit the form. 
It will refresh the page.

This was working with our old version  v3.0.0-beta.14

**Home.Component.html**
  <form [formGroup]="stockForm" (ngSubmit)="onSubmit()">
    <label>Enter Stock code:
      <input formControlName="stockcode" placeholder="Enter stock code">
    </label>
    <button type="submit">Save</button>
  </form>

**Home.Component.ts**

import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {

  message: string;
  stockForm: FormGroup;
  submitted = false;
  constructor(private formBuilder: FormBuilder
  ) { }

  ngOnInit() {
    this.stockForm = this.formBuilder.group({
      stockcode: ['', Validators.required]
    });
  }

  onSubmit() {
    this.submitted = true;
    console.log(JSON.stringify(this.stockForm.value));
  }
}

is it due to the lazy loading changes in v3.0.0-beta.18 release? I have noticed that if you wait for 5-10 then it will work fine.

![image](https://user-images.githubusercontent.com/49240619/57478791-79100d00-7261-11e9-9227-cf395b2740d0.png)

**Comment by joeldenning** [comment] 2019-05-10 21:56
Hmm I don't know how this would be related to the beta.19 or beta.20 changes.

Could you push up an example repo for me to take a look at?

**Comment by HemendPatel63** [comment] 2019-05-13 21:26
Agree - this is not related to new changes. I will create a repo and share it.

**Comment by joeldenning** [comment] 2019-06-06 21:37
The first thing to check with this is if you are calling `event.preventDefault()` on form submission, which is what prevents the page reload.

I am closing this because I don't have a way to reproduce the problem. Feel free to comment further or reopen with a repo that reproduces the problem.

**Closed by joeldenning** 2019-06-06 21:37 UTC
