### ISSUE TITLE
 CORS policy: No 'Access-Control-Allow-Origin' 

### ISSUE THREAD

**Issue by HemendPatel63** [CanopyTax/single-spa-angular#74] opened 2019-05-13 21:29 UTC
Hi @joeldenning,

Access to script at 'http://localhost:8086/main.js' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

If we create two separate website in window IIS and try to load it with single spa.

"imports": {
          "app1": "http://localhost:8651/main.js",
          "app2": "http://localhost:8600/main.js",
          "single-spa": "https://unpkg.com/single-spa@4.3.2/lib/system/single-spa.min.js"
        }

**Comment by joeldenning** [comment] 2019-05-13 23:41
What version of angular are you using?

The latest version of Angular [has Access-Control-Allow-Origin headers](https://github.com/angular/angular-cli/blob/5770762ac193c323310f53f6c37288275552fc7c/packages/angular_devkit/build_angular/src/dev-server/index.ts#L261) which solve this issue.

If you're on an older version, I can add some code to single-spa-angular to fix it.

**Comment by HemendPatel63** [comment] 2019-05-14 01:24
I am using the version 7.3.6. Let me check if I have missed any thing.

**Comment by joeldenning** [comment] 2019-05-14 03:00
One gotcha with browsers and headers is that if you go directly to a URL, the server will not send CORS headers and the browser will cache the headers. So then when you access the URL from a different domain the cached headers don't have CORS and it fails.

So maybe clear cache?

If not that, maybe push a repo that reproduces the problem?

**Comment by HemendPatel63** [comment] 2019-05-14 14:36
I have created repo @https://gitlab.com/Hemendra.patel/spaapps
I have followed below step to do the setup


npm i
npm run build:single-spa
appcmd add site /name:navbar /id:70 /bindings:http/*:88: /physicalPath:C:\SPA\navbar\dist\navbar
appcmd set config navbar /section:system.webServer/directoryBrowse /enabled:true


npm i
npm run build:single-spa
appcmd add site /name:angularspa1 /id:71 /bindings:http/*:89: /physicalPath:C:\SPA\angularspa1\dist\angularspa1
appcmd set config angularspa1 /section:system.webServer/directoryBrowse /enabled:true


npm i
npm run build:single-spa
appcmd add site /name:angularspa2 /id:72 /bindings:http/*:90: /physicalPath:C:\SPA\angularspa2\dist\angularspa2
appcmd set config angularspa2 /section:system.webServer/directoryBrowse /enabled:true

npm i
npm run build:single-spa
appcmd add site /name:portal /id:73 /bindings:http/*:91: /physicalPath:C:\SPA\portal
appcmd set config portal /section:system.webServer/directoryBrowse /enabled:true


now browse the potal app to get the issue - http://localhost:91

**Comment by amaneer94** [comment] 2019-05-21 17:01
I got the same issue when trying to link build main.xxxxxxxxxxx.js file which is hosted on any other server i.e. Apache Local www/html folder.
![Screenshot from 2019-05-21 21-57-03](https://user-images.githubusercontent.com/16270049/58115649-f2214400-7c13-11e9-9640-3b4d7b31ae88.png)

**Comment by joeldenning** [comment] 2019-05-21 17:16
@amaneer94 it sounds like you’re not using Ng serve (which uses webpack-dev-server that is configured to send CORS headers).

So your problem is not related to single-spa or single-spa-angular. Just CORS. To get Apache to send CORS headers, see https://enable-cors.org/server_apache.html

**Comment by joeldenning** [comment] 2019-05-21 17:18
@HemendPatel63 your problem is not related to single-spa or single-spa-angular. It’s just related to CORS and IIS.

You need to configure IIS to send Access-Control-Allow-Origin headers. See https://docs.microsoft.com/en-us/iis/extensions/cors-module/cors-module-configuration-reference.

I’m closing this since it’s not related to single-spa-angular.

**Closed by joeldenning** 2019-05-21 17:18 UTC

**Comment by HemendPatel63** [comment] 2019-05-22 13:48
I am so very thankful for your time!. 
Yes - Its require IIS  core extension.

**Comment by mohamedJeddi** [comment] 2019-08-27 09:57
Hi @HemendPatel63 how id you fix this issue using IIS core extension please ,?!!! Because i have the same issue !!!

**Comment by mohamedJeddi** [comment] 2019-08-28 14:22
Okay thanks for your response and I'll will try it

Le mer. 28 août 2019 à 3:20 PM, HemendPatel63 <notifications@github.com> a
écrit :
