### ISSUE TITLE
Application unexpected behavior on clicking browser history back/forward buttons

### ISSUE THREAD

**Issue by amaneer94** [CanopyTax/single-spa-angular#78] opened 2019-05-22 11:41 UTC
When I navigate through the application's router links all work perfectly. But when I try to navigate back using the browser's back button application shows multiple instances of angular components.

```
// app-routing.ts (navbar app)
const routes: Routes = [
  {
    path: '', component: NavbarComponent,
    children: [
      { path: 'login', component: LoginComponent },
      { path: 'dashboard', component: DashboardComponent },
    ]
  },
  { path: '**', component: NavbarComponent }
];

```
Please see the attached gif.
![Peek 2019-05-22 16-33](https://user-images.githubusercontent.com/16270049/58171870-64dffd00-7cb0-11e9-990d-8825ac032c28.gif)

**Comment by amaneer94** [comment] 2019-05-22 11:52
One more thing this warning shows in console logs
`
core.js:16834 Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?
`

**Comment by joeldenning** [comment] 2019-05-25 06:40
The console warning is unrelated. See #53 

Could you push a minimal repo that reproduces the error shown in the gif? I won't be able to look at this until next week, but a github repo that reproduces the issue would help me debug a lot.

**Comment by amaneer94** [comment] 2019-05-29 12:03
@joeldenning, After a lot of exploring the topics on Angular router-outlet, ngZones, Change Detection and of course your discussion in issue https://github.com/CanopyTax/single-spa-angular/issues/53 . I tried the following piece of code in the sub-application's root component's `constructor` and it solved my UI problem also application became stable like magic.

```
import { Component, OnInit, ChangeDetectorRef, NgZone } from '@angular/core';
import { Router, NavigationEnd } from '@angular/router';
import { filter } from 'rxjs/operators';

@Component({
  selector: 'app-root',
  templateUrl: './app-root.component.html',
  styleUrls: ['./app-root.component.css']
})
export class MainContentComponent implements OnInit {

  constructor(
    public router: Router,
    public cd: ChangeDetectorRef,
    public ngZone: NgZone
    ) {
    this.router.events.pipe(filter(e => e instanceof NavigationEnd)).subscribe((e: NavigationEnd) => {
      this.ngZone.run(() => {
        this.cd.detectChanges();
      })
    })
  }
}
```
I dont know whether this is the best practice or not, if you can analyse it and let me know. Thanks!

**Comment by joeldenning** [comment] 2019-06-06 21:34
I am still unable to reproduce this problem. If anyone can push a repo that reproduces this would help. The back button works when navigating at http://coexisting-angular-microfrontends.surge.sh/.

> I dont know whether this is the best practice or not, if you can analyse it and let me know. Thanks!

Your code is forcing an [angular change detection tick](https://angular.io/api/core/testing/tick) every time that the route changes. Which is pretty similar to what older versions of single-spa-angular did before there was a big fix in [single-spa@4.3.0](https://github.com/CanopyTax/single-spa/releases/tag/v4.3.0) that made it unnecessary. Once single-spa@4.3.0 was released, we removed the angular tick code from single-spa-angular and things have been working fine. Since you are running into a situation where it isn't working fine, we might need to look at it again.

I am going to close this since I have no way to reproduce. Please reopen if the error persists and there's a way to reproduce.

**Closed by joeldenning** 2019-06-06 21:34 UTC

**Comment by amaneer94** [comment] 2019-07-24 10:07
Hi @joeldenning 
I am still having the same problem with browser back/forward buttons even I have upgraded the single-spa-angular to ^3.0.1.
I have been able to prepare a repo, you would be able to produce the issue.

https://github.com/amaneer94/single-spa

**Comment by amaneer94** [comment] 2019-07-24 10:09
![Peek 2019-07-24 15-04](https://user-images.githubusercontent.com/16270049/61785386-0dcbe500-ae25-11e9-88b4-5b65007a1cce.gif)

**Comment by amaneer94** [comment] 2019-07-31 16:12
Hi, @joeldenning I am looking forward to hearing from you.

**Comment by joeldenning** [comment] 2019-08-16 05:19
I will look at this tomorrow, in conjunction with looking at #94

**Comment by gustavo9601** [comment] 2024-07-12 22:18
> Hi @joeldenning, After a lot of exploring the topics on Angular router-outlet, ngZones, Change Detection and of course your discussion in issue [#53 (comment)](https://github.com/single-spa/single-spa-angular/issues/53#issuecomment-490276658) . I tried the following piece of code in the sub-application's root component's `constructor` and it solved my UI problem also application became stable like magic.
> 
> ```
> import { Component, OnInit, ChangeDetectorRef, NgZone } from '@angular/core';
> import { Router, NavigationEnd } from '@angular/router';
> import { filter } from 'rxjs/operators';
> 
> @Component({
>   selector: 'app-root',
>   templateUrl: './app-root.component.html',
>   styleUrls: ['./app-root.component.css']
> })
> export class MainContentComponent implements OnInit {
> 
>   constructor(
>     public router: Router,
>     public cd: ChangeDetectorRef,
>     public ngZone: NgZone
>     ) {
>     this.router.events.pipe(filter(e => e instanceof NavigationEnd)).subscribe((e: NavigationEnd) => {
>       this.ngZone.run(() => {
>         this.cd.detectChanges();
>       })
>     })
>   }
> }
> ```
> 
> I dont know whether this is the best practice or not, if you can analyse it and let me know. Thanks!

Thank you very much, It still work in angular 17 you saved my day :D
